### ISSUE TITLE
License for Workshop Materials

### ISSUE THREAD

**Issue by kochbj** [maxwshen/iap-cidl#2]
Hi Max (and Fredrik),

I've found these workshop materials incredibly useful; thanks for creating them! I'm writing a literature review about machine learning and causal inference and was wondering if you'd considered putting a license on these materials. I'd love to reproduce some simple figures from the slides, with your permission.

Thanks for your time,
Bernie

**Comment by maxwshen** [comment]
That's great to hear! Please feel free to use them in any way you would
like, just please cite our work.

Best,
Max

**Comment by kochbj** [comment]
Great. Thanks Max!
